Added visual effects
OLODiman11/tetris pull request #14
Opened 2024-03-03 18:15 UTC by OLODiman11

Added:
- Movement/rotation transitions (tweening)
- Row deletion particle effect

Holding left/rights button has a visual bug. Will fix after major refactoring.

https://github.com/OLODiman11/tetris/assets/88656576/82eefd29-5c23-4d1d-9cc5-4c1a2fdccf13

2024-03-04 06:34 UTC, S1rMekr commented on scenes/particles_test.tscn
Do we need this scene? I just can't if it's used somewhere in the project

2024-03-04 06:43 UTC, S1rMekr requested changes
Hello, _OLOLODiman11!_ I really appreciate your work but I have **some** questions if you don't mind.

1) Do we need s **particle_test.tscn**? I don't see if it's whether used.
2) It appears that we have a folder "**shape_previews**" with scripts. Maybe we should move them to the _scripts_ folder (It's more about the refactoring of all our code). What do you think?

2024-03-04 08:04 UTC, OLODiman11 commented on scenes/particles_test.tscn
Maybe i'm stupid but your main comment doesn't have a reply button. About moving scripts. Maybe we should do it on the refactoring stage?

2024-03-04 08:06 UTC, S1rMekr commented on scenes/particles_test.tscn
I agree with you!
![Uploading VdvMGQWf2t0.jpg…]()

2024-04-03 06:29 UTC, S1rMekr approved these changes
yea

2024-04-03 06:38 UTC, merged